"""autogenerated by genpy from chisel_ros/ChunkMessage.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ChunkMessage(genpy.Message):
  _md5sum = "2b6f25fa6b6ba9fc3cd619253cab4653"
  _type = "chisel_ros/ChunkMessage"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

#Chunk ID spatial position
int32 ID_x
int32 ID_y
int32 ID_z

#Chunk spatial hash value
int64 spatial_hash

#Size of a voxel in meters
float32 resolution_meters

#number of voxels in each dimension
int32 num_voxels_x
int32 num_voxels_y
int32 num_voxels_z

#Binary serialization of distances/weights
uint32[] distance_data

#Binary serialization of colors/weights
uint32[] color_data

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','ID_x','ID_y','ID_z','spatial_hash','resolution_meters','num_voxels_x','num_voxels_y','num_voxels_z','distance_data','color_data']
  _slot_types = ['std_msgs/Header','int32','int32','int32','int64','float32','int32','int32','int32','uint32[]','uint32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ID_x,ID_y,ID_z,spatial_hash,resolution_meters,num_voxels_x,num_voxels_y,num_voxels_z,distance_data,color_data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ChunkMessage, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ID_x is None:
        self.ID_x = 0
      if self.ID_y is None:
        self.ID_y = 0
      if self.ID_z is None:
        self.ID_z = 0
      if self.spatial_hash is None:
        self.spatial_hash = 0
      if self.resolution_meters is None:
        self.resolution_meters = 0.
      if self.num_voxels_x is None:
        self.num_voxels_x = 0
      if self.num_voxels_y is None:
        self.num_voxels_y = 0
      if self.num_voxels_z is None:
        self.num_voxels_z = 0
      if self.distance_data is None:
        self.distance_data = []
      if self.color_data is None:
        self.color_data = []
    else:
      self.header = std_msgs.msg.Header()
      self.ID_x = 0
      self.ID_y = 0
      self.ID_z = 0
      self.spatial_hash = 0
      self.resolution_meters = 0.
      self.num_voxels_x = 0
      self.num_voxels_y = 0
      self.num_voxels_z = 0
      self.distance_data = []
      self.color_data = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3iqf3i.pack(_x.ID_x, _x.ID_y, _x.ID_z, _x.spatial_hash, _x.resolution_meters, _x.num_voxels_x, _x.num_voxels_y, _x.num_voxels_z))
      length = len(self.distance_data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.pack(pattern, *self.distance_data))
      length = len(self.color_data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.pack(pattern, *self.color_data))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.ID_x, _x.ID_y, _x.ID_z, _x.spatial_hash, _x.resolution_meters, _x.num_voxels_x, _x.num_voxels_y, _x.num_voxels_z,) = _struct_3iqf3i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.distance_data = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.color_data = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3iqf3i.pack(_x.ID_x, _x.ID_y, _x.ID_z, _x.spatial_hash, _x.resolution_meters, _x.num_voxels_x, _x.num_voxels_y, _x.num_voxels_z))
      length = len(self.distance_data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.distance_data.tostring())
      length = len(self.color_data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.color_data.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.ID_x, _x.ID_y, _x.ID_z, _x.spatial_hash, _x.resolution_meters, _x.num_voxels_x, _x.num_voxels_y, _x.num_voxels_z,) = _struct_3iqf3i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.distance_data = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.color_data = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_3iqf3i = struct.Struct("<3iqf3i")
